gridscale/gsclient-go

README.md
request.go
server.go

Note: seems to have pulled in some unmerged commits from @fkr 
@fkr Is this considered a breaking change? If so maybe I need some sort of version update, or tag the commit?

Update package install location

---

loadbalancer.go

During integration with Terraform, I found this bug.

Fix labels type

---

examples/loadbalancer.go
loadbalancer.go
loadbalancer_test.go

This unittest is based on mocked responses from gridscale API.

Add unittest for loadbalancer

---

go.mod

From `gsclient-go` to `github.com/gridscale/gsclient-go`

fix gomod module

---

CHANGELOG.md
README.md
config.go

Cleanup v2.2.2

---

README.md
storage.go
storage_test.go

The implementation of storage cloning endpoint `https://api.gridscale.io/objects/storages/{storage-uuid}/clone`. This PR also includes `CloneStorage`'s unittest.

Implementation of storage cloning

---

CHANGELOG.md
README.md
config.go
go.mod

- Update CHANGELOG.
- Update README.
- Update version number in code + gomod.

Cleanup for v3

---

CHANGELOG.md

cleanup v3.0.1

---

storage.go

https://gridscale.io/en//api-documentation/index.html#operation/updateStorage

Storage can be increased its speed via UpdateStorage

---

CHANGELOG.md
RELEASECHECKLIST.md
config.go

- Update Changelog.
- Update version header.

Cleanup v3.1.0

---

storage_backup.go
storage_backup_test.go

- Add storage backup functionalities.
- Add storage backup unit tests.

Add storage backup functionalities

---

storage_backup_schedule.go
storage_backup_schedule_test.go

- Add storage backup schedule's functionalities.
- Add storage backup schedule's unit tests.

Add storage backup schedule's functionalities

---

event.go
examples/marketplaceApp.go
examples/storagebackupschedule.go
firewall.go
ip.go
isoimage.go
label.go
loadbalancer.go
location.go
marketplace_application.go
network.go
objectstorage.go
paas.go
server.go
serverip.go
serverisoimage.go
servernetwork.go
serverstorage.go
snapshot.go
snapshotscheduler.go
sshkey.go
storage.go
storage_backup.go
storage_backup_schedule.go
template.go
types.go

- Added examples: marketplace application, storage backup.
- Added APIs for easy development (can be used for mocking gsclient-go).
- Fixed an error occurring when parsing an empty string to a GSTime variable.

Add examples and improve dev experience

---

CHANGELOG.md
README.md
config.go

Cleanup v3.2

---

storage_backup_schedule.go

Fix issue https://github.com/gridscale/gsclient-go/issues/145

Change json field `storage_backups`'s name to `storages_backups`

---

CHANGELOG.md
config.go

Update changelog and version number.

Cleanup v3.2.1

---

.travis.yml

Making a release draft when a tag is pushed

---

.github/workflows/go.yml

Add config file for gh actions.

Apply github actions

---

marketplace_application.go
marketplace_application_test.go
storage_backup.go
storage_backup_test.go

- Fixed API endpoint of storage backup rollback.
- Fixed typo in struct `MarketplaceApplicationMetadata`.

Fix issues #149 and #148

---

request.go

Just omit X-Auth-UserID and X-Auth-Token when they are empty.

Omit UserID and Token when they are empty

---

release-checklist.md

Just update release checklist.

Update release checklist

---

ip.go
server.go

- Fix issue (160)[https://github.com/gridscale/gsclient-go/issues/160].
- Fix doc of `HardwareProfile`.

Remove incorrect IP relations and update doc of `HardwareProfile`

---

README.md

Remove L3 security issue from known issue.

Remove L3 security from known issue

---

CHANGELOG.md
config.go

- Update changelog.
- Update version number in config.

Cleanup for v3.3.0

---

CHANGELOG.md
config.go

- Update changelog.
- Update version number in config.

Cleanup v3.3.1

---

paas.go

Ref #192. Changes:
- Add missing `Autoscaling` field.

add `Autoscaling` field

---

request.go

Fixes #201. When retrying a request, recreate that request before sending it to gs backend.

Recreate request when retrying

---

server.go
storage.go

- Remove unnecessary server hw profiles: "q35_nested". 
- Add missing field `StorageVariant ` to `StorageProperties`.

Add missing fields & Remove unnecessary server hw profiles.

---

network.go

Just add DHPC options to network. Ref #206

Add DHPC options to network
