request.go
as `json.Unmarshal(iostream, &errorMessage)` already takes the pointer (by using `&` symbol). So that we don't need to use new() function. Also it is better to avoid using many new() as the function will create a variable which will escape from our stack memory.
=> Initialize RequestError Instance instead of a pointer

request.go, server.go
I have removed unnecessary new() causing variables escaping from stack memory.
=> remove unnecessary new()

loadbalancer.go, server.go, server_test.go
Somehow this field disappeared from our API docs. I found out that it is just an optional field. If it is set, all arrays of its sub-fields have to be filled with either empty "[]" or some elements. This means if one sub-field is filled and others are empty, those empty fields still have to be presented (with "[]" as values).
=> Bring back "Relations" field when creating a server.

config.go, event.go, examples/server.go, examples/storage.go, firewall.go, ip.go, isoimage.go, label.go, loadbalancer.go, location.go, network.go, objectstorage.go, paas.go, paas_test.go, request.go, server.go, server_test.go, serverip.go, serverisoimage.go, servernetwork.go, serverstorage.go, snapshot.go, snapshotscheduler.go, sshkey.go, storage.go, storage_test.go, template.go, types.go
- gsclient-go is now more friendly to other developers (in term of document).
- Some fields are optional (according to gridscale's API documentation).
- 424 now also causes retrying.
=> Friendly godoc & some minor updates.

CHANGELOG.md, common.go, config.go, go.mod, request.go, request_test.go, server_test.go
provisioning k8s cluster depends mainly on gsclient-go/Terraform. Currently, gsclient-go only retries API errors with status code > 500 and 424.  However, provisioning k8s cluster sometimes fails due to network hiccup (conn resets and timeouts mostly).
so, we need to include the following issues to be handled by gs-client retry logic:
- networking issues (timeouts, conn resets, conn refused, etc) for read-only requests (e.g, GET)
- networking issues with connection refused to write requests (e.g, POST, PATCH, and DELETE )
- simple backoff request in case of retrying error.
=> Retry network failures

CHANGELOG.md, go.mod
Fix incompatible major version when using gomod due to missing `/v2` suffix in module path of `go.mod` file
=> Add `/v2` suffix in module path of `go.mod` file

CHANGELOG.md, README.md, label.go
Add a notice to README, and add comments to the code about deprecating label's create/delete functions.
=> `DEPRECATE` label's create/delete functions.

request.go
When the context is expired, `execute` function is supposed to stop. In the previous version, I thought `err.Timeout()` would catch the deadline of the context (`execute` keeps retrying even if the context is done. It still returns the context error, but the context error becomes retryable error). The solution is to catch the context error early and also when the http request returns error (if the context is done, `httpClient.Do` also returns error).
=> Fix bug: "still retrying when the context is already expired"

README.md, examples/label.go, label.go, label_test.go
Since we already deprecated label's create/delete functions, and they are already removed from gridscale's official API docs, this PR is to remove these functions from gridscale go SDK. I also updated the readme file.
=> remove label create/delete functions

README.md, common.go, examples/firewall.go, examples/ip.go, examples/isoimage.go, examples/label.go, examples/loadbalancer.go, examples/network.go, examples/objectstorage.go, examples/paas.go, examples/server.go, examples/snapshot.go, examples/snapshotschedule.go, examples/sshkey.go, examples/storage.go, examples/template.go, go.mod, paas.go, paas_test.go, vendor/modules.txt
This update is for gscloud.
- K8S support (get k8s config, renew k8s cluster's credentials).
- Replace wrong imported gsclient-go path `github.com/gridscale/gsclient-go` with `github.com/gridscale/gsclient-go/v3` in Readme and examples.
=> K8S support & fix some minor issues 

client.go, client_test.go, config.go, request.go
- Custom HTTP headers can be attached via `client.WithHTTPHeaders(map[string]string)` function.
- Existing HTTP headers can be replaced via `client.WithHTTPHeaders(map[string]string)` function by inputting the headers' name and their new values. E.g: 
`client.WithHTTPHeaders(map[string]string{
"User-Agent": "Example-User-Agent"",
})`
- Use `Header.Set()` instead of `Header.Add()` since we don't want to append values to an existing header.
Fixes #124
=> Support custom HTTP headers

client.go, config.go, event.go, firewall.go, ip.go, isoimage.go, label.go, loadbalancer.go, location.go, network.go, objectstorage.go, paas.go, request.go, request_test.go, server.go, serverip.go, serverisoimage.go, servernetwork.go, serverstorage.go, snapshot.go, snapshotscheduler.go, sshkey.go, storage.go, template.go
Changes:
- function `execute()` is refactored to make it easier to test, and easier to handle error status codes.
- handle 429 (rate limit reached) by waiting until the rate limit is reset.
- some small refactored code lines (e.g renaming `request` struct, adding some comments, making logger global, etc.)
=> Dealing with rate limit

request.go, request_test.go
- Add 409 to retriable http code -> when 409 is return, the request will be sent again until timeout is reached.
- Add test case for 409 case.
=> Fix bug 164 - retry request when 409 is returned

common.go, common_test.go, request.go, request_test.go, server_test.go
If the error is type of RequestError, convert the error to RequestError and return it. This helps to solve the issue in gs tf provider [tf PR #107](https://github.com/gridscale/terraform-provider-gridscale/pull/107)
=> cast type of err in retryWithLimitedNumOfRetries

paas.go
The new API allows PaaS to be updated is `paas_service_template_uuid`: [PaaS Patch](https://gridscale.io/en/api-documentation/index.html#operation/updatePaasService)
=> PaaSServiceTemplateUUID can be updated

request.go
- Mask the credentials in HTTP header when printing the debug log. Only reveal the first 5 characters.
Solve issue #182
=> Mask the credentials in HTTP header when printing the debug log

common.go, config.go, request.go
Changes:
- Allow to set log level manually via `SetLogLevel` fucntion.
- Tracing of request (method) durations and status (successful or unsuccessful).
Improvement:
- Only delay after running a retriable function => runtime is reduced up to 60%. [More](https://github.com/gridscale/gsclient-go/issues/186#issuecomment-795466954)
=> Allow tracing of request durations & performance improvement

storage.go
Allow to define storage variant when creating a new storage. Allowed `StorageVariant` values: `DistributedStorageVariant`, `LocalStorageVariant`. When `StorageVariant` is not set, the backend will create a local storage as default.
=> Allow to define storage variant when creating a new storage

ip.go, isoimage.go, loadbalancer.go, paas.go, server.go, snapshot.go, storage.go, template.go
Ref #191. Temporarily add DEPRECATED notice to `CurrentPrice` field docs.
=> Add DEPRECATED notice to `CurrentPrice` field docs

README.md, client.go, examples/sslcert.go, loadbalancer.go, loadbalancer_test.go, ssl_certificate.go, ssl_certificate_test.go
Ref #194. Changes:
- Add SSL certificate CRUD operations.
- Add unit tests of SSL certificate.
- Add example of SSL certificate operations.
- Change `LetsencryptSSL` field in loadbalancer from `interface{}` to `*string` (because this field is string type and it is nullable).
- Add `CertificateUUID` field in loadbalancer, allow to use a custom certificate.
=> Add Certificate CRUD operations & fix loadbalancer SSL certificate issues

paas.go
Ref #197. @itakouna and I decided to use `service_template_uuid` instead of `paas_service_template_uuid `. What changes:
- The json field name of `PaaSServiceTemplateUUID` is changed to `service_template_uuid`. The reasons are: The backward compatibility is guaranteed and the json field name can be easily changed in the future (in case `paas_service_template_uuid ` is used in PaaS Update).
I did test the change by upgrading a k8s cluster from v11.18 to v1.19 ✔️
=> Correct service_template_uuid field in update PaaS request

.github/workflows/go.yml, config.go, go.mod, vendor/modules.txt
There is a bug in go which caused the body of a HTTP2 upgraded request disappears during retry. The issue occasionally happens when concurrency is used. To solve this issue, I force the http client to use HTTP 1.1 explicitly (no HTTP2 upgrade). Furthermore, update golang to  v1.16 in go.mod file.
=> Fix PROTOCOL_ERROR

README.md, config.go, event_test.go, firewall_test.go, ip_test.go, isoimage_test.go, label_test.go, loadbalancer_test.go, location_test.go, marketplace_application_test.go, network_test.go, objectstorage_test.go, paas_test.go, request.go, request_test.go, server_test.go, serverip_test.go, serverisoimage_test.go, servernetwork_test.go, serverstorage_test.go, snapshot_test.go, snapshotscheduler_test.go, sshkey_test.go, ssl_certificate_test.go, storage_backup_schedule_test.go, storage_backup_test.go, storage_test.go, template_test.go
Ref #200. Only 503 and 429 are retriable. Changes:
- Requests with 503 response code will be retried. If `Retry-After` response header is defined (x seconds), the next retry will be executed after  x seconds. If that header is not included, the next retry depends on settings of `gsclient-go` (`delayIntervalMilliSecs` and `maxNumberOfRetries`). When the retry count of a request reaches `maxNumberOfRetries`, `gsclient-go` return the last retry's error.
- Requests with 429 (rate-limit is reached) response code will also be retried when the rate-limit is reset. If the rate-limit is reached again, retry again in when the rate-limit is reset. There is no `maxNumberOfRetries` for 429 request retry.
- Update docs.
- Update unit tests.
**NOTE**: if the context is `Done()` before retrying (or …
=> Fix handling of retry-able requests 429 and 503

network.go, network_test.go
Ref #207. Changes:
- Add method `GetPinnedServerList` to list all pinned servers in a DHCP-enabled network.
- Add method `UpdateNetworkPinnedServer` to assign DHCP IP into a server.
- Add method `DeleteNetworkPinnedServer` to remove DHCP IP from a server.
- Add more unit tests.
=> Allow pinning server in DHCP-enabled network

examples/location.go, location.go, location_test.go
Ref #208. Changes:
- Add missing location properties.
- Add missing location endpoints (Create/Update/Delete).
- Add location example.
- Deprecated `Status` in location's properties.
=> Add missing location's endpoints/properties

client.go, request.go, types.go, usage.go, usage_test.go
Ref #208. Changes:
- Add usage getters (general, servers, distributed storages, rocket storages, storage backups, snapshots, templates, ISO Images, IP addresses, load balancers, PaaS services).
- Add unit tests for the new usage getter methods.
- Allow query parameters to `gsRequest`.
- More robust debugging log (print the URL after preparing the request).
- Add method `String()` to `GSTime` struct to allow represent `GSTime` in the desired string.
=> Add usage query (project/contract level)

client.go, storage_backup_schedule.go, storage_backup_schedule_test.go
Ref #210. Changes:
- Add storage backup location API endpoint.
- Add method `GetStorageBackupLocationList` to fetch a list of available location used to store backups.
- Allow users to set location for backup in backup schedule.
- Update unit test.
=> Add backup location to storage backup schedule.

server.go
Allow update server's hw profile in PATCH request, according to [docs](https://gridscale.io/en/api-documentation/index.html#operation/updateServer).
=> Allow update server's hw profile in PATCH request

network.go
DHCP options that can be set to null to be removed are:
- `DHCPGateway`
- `DHCPDNS`
- `DHCPReservedSubnet`
Note: `DHCPRange` cannot be set to null.
=> Allow to remove DHCP options (except DHCPRange)

network.go, paas.go
Changes:
- Add `network_uuid` to `PaaSServicePropertie` (GET), `PaaSServiceCreateRequest` (POST), `PaaSServiceUpdateRequest` (PATCH).
- Add list of `NetworkPaaSService` which shows relations of a network and PaaS services when getting a network.
=> Allow to attach PaaS service to a private network

network.go
Those `dhcp_*` in network update request are optional => they need to be omitted when not set.
=> Add missing `omitempty` to dhcp update fields

request.go
Changes:
- Add retry when the backend return http error code 424 (usually caused by locked object), or 500.
=> add retry when error code 424 (locked object), 500

paas.go
Ref [getPaasServiceTemplates](https://gridscale.io/en//api-documentation/index.html#operation/getPaasServiceTemplates). Changes:
- Add StorageType to paas template's properties.
=> add StorageType to paas template
